#!/bin/bash
### BEGIN INIT INFO
# Provides:          broadcast_ip_via_mqtt
# Required-Start:    $local_fs $syslog $network mosquitto raspberry-wifi-conf
# Required-Stop:     $local_fs
# Default-Start:     3 4 5
# Default-Stop:      0 1 6
# Short-Description: broadcast_ip_via_mqtt
### END INIT INFO

nohup /usr/local/bin/broadcast_ip_via_mqtt $1 &